config/routes.rb
JamWithFriends::Application.routes.draw do
  get "jam_managements/show", to: 'jam_managements#show', as: "jam_managements_show" 
  get "registrations/after_sign_up_path_for"
  root "home#index"
  get "search/index", to: 'search#index', as: "search"
  get "jam_managements/edit_candidates", to: 'jam_managements#edit_candidates', as: "edit_candidates"
  get "jam_managements/update_candidates", to: 'jam_managements#update_candidates', as: "update_candidates"

  get "jam_managements/candidate", to: 'jam_managements#candidate', as: "candidate_to_jam"
  get "jam_managements/withdraw_candidate", to: 'jam_managements#withdraw_candidate', as: "withdraw_candidate_from_jam" 
  get "jam_managements/refuse_infite", to: 'jam_managements#refuse_invite', as: 'refuse_invitation_from_jam'

  get "jam_managements/edit_invite", to: 'jam_managements#edit_invite', as: "edit_invite"
  get "jam_managements/update_invite", to: 'jam_managements#update_invite', as: "update_invite"

  resources :instruments
  resources :genres
  devise_for :users, :controllers => { :registrations => "registrations", :passwords => "passwords"  }
  resources :profile, only: [:show, :edit, :update]
  resources :messages
  resources :conversations
  resources :jams
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable
  has_many :instrxps
  has_many :instruments, through: :instrxps
  has_many :guassociations
  has_many :genres, through: :guassociations
  has_one :location
  accepts_nested_attributes_for :instruments, :genres
  validates :email, uniqueness: true
  validates :name, uniqueness: true
  accepts_nested_attributes_for :instrxps
  accepts_nested_attributes_for :instruments

  has_attached_file :photo

  has_many :candidates
  has_many :candidate_instruments, through: :candidates, :source => :instrument
  has_many :candidate_jams, through: :candidates, :source => :jam

  has_many :invites
  has_many :invited_instruments, through: :invites, :source => :instrument
  has_many :invited_jams, through: :invites, :source => :jam  



  def mail_email(object)
    email
  end



  def mailboxer_email(object)
  #Check if an email should be sent for that object
  #if true
  return :email
  #if false
  # return nil
end


# first version WORS, without string sanitation!
  # scope :search_by_genre, ->(genre) { joins(:genres).where('genres.id' => genre)}
  # scope :search_by_instrument, ->(instrument) { joins(:instruments).where('instruments.id' => instrument)}
  # scope :search_by_location, ->(location) { joins(:location).where('locations.id' => location)}

#second version - WORKS! - with string sanitization
  # def self.search_by_genre(query)
  #   joins(:genres).where('genres.id LIKE :query', :query  => "%#{query}%")
  # end
  # def self.search_by_genre(query)
  #   joins(:genres).where('genres.id' => genre)
  # end

  # def self.search_by_instrument(query)
  #   joins(:instruments).where('instruments.id LIKE :query', :query  => "%#{query}%")
  # end

  # def self.search_by_location(query)
  #   joins(:location).where('locations.id LIKE :query', :query  => "%#{query}%")
  # end

# third version - all rolled together
  # scope :search_by_genre, ->(query) { joins(:genres).where('genres.id LIKE :query', :query => "#{query}")}
  scope :search_by_genre, ->(query)     { includes(:genres).where({ genres: { id: query}})}
  scope :search_by_instrument, ->(query) { includes(:instruments).where({ instruments: { id: query}})}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 # before_filter :authenticate_user!, :except => [:new, :create, :destroy, :show_profile]

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
      <li class="list-group-item">

       <div class="profile-image">
        <%= link_to(image_tag(user.photo.url, class: "profile-image-inner"), profile_path(user)) %>
       </div>
       <div class="basic-info-top">
          <div class= "basic-info-content basic-info-name">
            <%= link_to user.name, profile_path(user) %>
          </div>
          <div class= "basic-info-content basic-info-bottom">
            <%= user.genres.first.name %> <%= user.genres.count > 1 ? "and more ..." : ""  %>
          </div>
          <div class= "basic-info-content basic-info-bottom">
            <% i = user.instrxps.order(since: :asc).first %>
            <%= i.instrument.name %><%=" (#{2014-i.since}yrs)"%><%= user.instruments.count > 1 ? " +others" : ""  %>
          </div>
          <div class="basic-info-bottom-content">
            <div class="contact">            
             <% if user_signed_in?  %>
                <%= link_to :contact, new_message_path(:receiver => "#{user.id}") %>
              <% else %>
               <%= link_to content_tag(:span, "contact"), new_user_registration_path %>
              <% end %>
            </div>
          </div>  
        </div>
      </li>

app/views/users/edit.html.erb
<h3> add an instrument to your profile? <h3>
<%= form_for @current_user do |f|  %>
    <h2> instruments </h2>
    <% Instrument.all.each do |instrument| %>
      <%= check_box_tag "user[instrument_id][]", instrument.id, @current_user.instrument_ids.include?(instrument.id), id: dom_id(instrument) %>
      <%=label_tag dom_id(instrument),  instrument.name %> <br> 
    <% end %>
    <h2> generes </h2>
    <% Genere.all.each do |genere| %>
      <%= check_box_tag "user[genere_id][]", genere.id, @current_user.genere_ids.include?(genere.id), id: dom_id(genere) %>
      <%=label_tag dom_id(genere),  genere.name %> <br> 
    <% end %>
    <h2> location </h2>
    <%= f.label :location %>
    <%= f.text_field :location, value: "#{@current_user.location.address}" %>
    <br>
    <%= f.label :radius %>
    <%= f.text_field :radius, value: "#{@current_user.location.radius}" %>
    <br>
    <%= f.submit %>
  <% end %>
  

app/views/users/show.html.erb
<h2>your current preferences </h2>
<h3> Instruments </h3>

<% current_user.instruments.each do |instrument| %>
  <p><%= instrument.name %></p>
<% end %>

<h3> Generes </h3>
<% current_user.generes.each do |generes| %>
  <p><%= generes.name %></p>
<% end %>

<h3> Location </h3>
<p>Address: <%= current_user.location.address %></p>
<p>Latitude: <%= current_user.location.latitude %></p>
<p>Longitude: <%= current_user.location.longitude %></p>
<p>Radius: <%= current_user.location.radius %>   (miles)</p>

<%= link_to "edit profile", edit_user_path  %>
<%= link_to "back home", root_path %>