config/routes.rb
JamWithFriends::Application.routes.draw do
  get "jam_managements/show", to: 'jam_managements#show', as: "jam_managements_show" 
  get "registrations/after_sign_up_path_for"
  root "home#index"
  get "search/index", to: 'search#index', as: "search"
  get "jam_managements/edit_candidates", to: 'jam_managements#edit_candidates', as: "edit_candidates"
  get "jam_managements/update_candidates", to: 'jam_managements#update_candidates', as: "update_candidates"

  get "jam_managements/candidate", to: 'jam_managements#candidate', as: "candidate_to_jam"
  get "jam_managements/withdraw_candidate", to: 'jam_managements#withdraw_candidate', as: "withdraw_candidate_from_jam" 
  get "jam_managements/refuse_infite", to: 'jam_managements#refuse_invite', as: 'refuse_invitation_from_jam'

  get "jam_managements/edit_invite", to: 'jam_managements#edit_invite', as: "edit_invite"
  get "jam_managements/update_invite", to: 'jam_managements#update_invite', as: "update_invite"

  resources :instruments
  resources :genres
  devise_for :users, :controllers => { :registrations => "registrations", :passwords => "passwords"  }
  resources :profile, only: [:show, :edit, :update]
  resources :messages
  resources :conversations
  resources :jams
end

app/models/jam.rb
class Jam < ActiveRecord::Base
  belongs_to :location
  belongs_to :user


  has_many :candidates
  has_many :candidate_instruments, through: :candidates, :source => :instrument
  has_many :candidate_users, through: :candidates, :source => :user

  has_many :invites
  has_many :invited_instruments, through: :invites, :source => :instrument
  has_many :invited_users, through: :invites, :source => :user

  accepts_nested_attributes_for :invites, :candidates
  scope :search_by_instrument, ->(query) { includes(:candidate_instruments).where({ instruments: { id: query}})}
end

app/controllers/jams_controller.rb
class JamsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]

  def index
    @jams = Jam.where(user_id: current_user.id)
    @jams_candidate = Candidate.where(user_id: current_user.id).collect {|i| i.jam}
    @jams_invited = Invite.where(user_id: current_user.id).collect {|i| i.jam}
    find_candidable_jams
  end

  def new
    @jam = Jam.new 
  end

  def create
    safe_params
    @jam = Jam.new
    instruments_required
    basic_jam
  end

  def show
    find_jam
    if @jam.user.id == current_user.id
      render 'show'
    elsif @jam.invited_users.include?(current_user)
      @instrument = Invite.where(jam_id: @jam.id, user_id: current_user.id).first.instrument
      render 'show_invited'
    elsif @jam.candidate_users.include?(current_user)
      @instrument = Candidate.where(jam_id: @jam.id, user_id: current_user.id).first.instrument
      render 'show_candidate'
    else
      candidable_instruments
      render 'show_candidable'
    end    
  end

  def edit
    find_jam
  end

  def update
    safe_params
    find_jam
    basic_jam
  end

  def destroy
    find_jam
    @jam.destroy
    flash[:notice] = "jam deleted"
    redirect_to root_path
  end

private

  def find_jam
    sea = params[:id].to_i
    @jam = Jam.find sea
  end

  def find_candidable_jams
    @jams_candidable = []
    current_user.instruments.each do |instrument|
      Jam.search_by_instrument(instrument.id).each do |j|
        unless already_in_the_jam(j)
          @jams_candidable << j 
        end
      end
    end
  end
  
  def safe_params
    @safe_params = params.require(:jam).permit(:location, :date, candidate_instruments: [])
  end

  def basic_jam
    instruments_required
    @jam.date = @safe_params[:date]
    @jam.location = Location.create :address => @safe_params[:location]
    @jam.user = current_user
    @jam.save
    if !@jam.errors.messages.empty?
      @errors = @jam.errors
      render 'jam_not_created'
    else
      redirect_to @jam
    end
  end

  def instruments_required
    @jam.candidates.each {|candidate| candidate.delete}
    @safe_params[:candidate_instruments].uniq.each do |i_id|
        unless i_id.empty?
        instrument = Instrument.find(i_id.to_i)  
          unless @jam.candidate_instruments.to_a.include?(instrument)
            @jam.candidate_instruments << instrument
          end
        end
    end
  end

  def already_in_the_jam(jam)
    if jam.candidate_users.include?(current_user) || jam.invited_users.include?(current_user) || jam.user.id == current_user.id
      true
    else
      false
    end
  end

  def candidable_instruments
    @instruments = @jam.candidate_instruments.uniq & current_user.instruments
  end


end

app/helpers/jams_helper.rb
module JamsHelper
end

app/views/jams/_jam.html.erb
<h3>Jam!!!</h3>
<p>When: <%= @jam.date %></p>
<p>Where: <%= @jam.location.address %></p>
<p>Organisers: <%= @jam.user.name %></p>
<p>Instruments:</p>
<ul>
  <% @jam.candidate_instruments.uniq.each do |i| %>
    <li><%= i.name %></li>
  <% end %>
</ul>
<p><%= link_to "back to jams", jams_path %></p>

app/views/jams/_jam_basics.html.erb
<%= form_for @jam do |j|%>
  <%= j.label :date %>
  <%= j.text_field :date %>
  <%= j.label :location %>
  <%= j.text_field :location, value: @jam.location ? @jam.location.address : "" %>
  <%= j.label :instruments %>
  <div class="instrument_choice">
    <%= j.collection_select :candidate_instruments, Instrument.all, :id, :name, {:include_blank => true, :selected => @jam.candidate_instruments.collect {|i| i.id}},{ multiple: true, :class => "chzn-search", "data-placeholder" => "Select Instrument(s)"}%>
  </div>
  <br>
  <%= j.submit %>
<% end %>

app/views/jams/edit.html.erb
<h1>Edit the jam Jam!</h1>
<%= render 'jam_basics' %>
<%= link_to 'delete_jam', jam_path, method: :delete,:confirm => 'Are you sure you want to delete this jam?' %>

app/views/jams/index.html.erb
<%= link_to "new jam?", new_jam_path %>
<p>your jams:</p>
<ul>
  <% @jams.each do |jam| %>
    <li><%= link_to jam.date, jam_path(jam) %></li>
  <% end %>
</ul>
<p>Jams you are candidated:</p>
<ul>
  <% @jams_candidate.each do |jam| %>
    <li><%= link_to jam.date, jam_path(jam) %></li>
  <% end %>
</ul>
<p>Jams you are invited:</p>
<ul>
  <% @jams_invited.each do |jam| %>
    <li><%= link_to jam.date, jam_path(jam) %></li>
  <% end %>
</ul>

<p>Jams you might be interested in:</p>
<ul>
  <% @jams_candidable.each do |jam| %>
    <li><%= link_to jam.date, jam_path(jam) %></li>
  <% end %>
</ul>

app/views/jams/jam_not_edited.html.erb
<%= @errors %>

app/views/jams/new.html.erb
<h1>New Jam!</h1>
<p>Fiagata!!!</p>
<%= render 'jam_basics' %>



  

app/views/jams/show.html.erb
<%= render 'jam' %>


  <%= link_to "add more instruments/ edit jam", edit_jam_path %><br>
  <%= link_to "Invite awesome people to the jam", jam_managements_show_path(:jam_id => @jam.id)%>

app/views/jams/show_candidable.html.erb
<%= render 'jam' %>
Do you want to candidate yourself to this jam?
<% @instruments.each do |i| %>
  <%= link_to "candidate me! as #{i.name}",candidate_to_jam_path(:jam_id => @jam.id, :instrument_id => i.id) %>
<% end %>

app/views/jams/show_candidate.html.erb
<%= render 'jam' %>
<p>you are candidate to this jam as <%= @instrument.name %>, wanna pull you candidacy?</p>
<%= link_to "pull candidacy as #{@instrument.name} player",withdraw_candidate_from_jam_path(:jam_id => @jam.id, :instrument_id => @instrument.id)  %>

app/views/jams/show_invited.html.erb
<%= render 'jam' %>
<p>you are invited to this jam as <%= @instrument.name %>, wanna pull that?</p>
<%= link_to "refuse invitation as #{@instrument.name} player",refuse_invitation_from_jam_path(:jam_id => @jam.id, :instrument_id => @instrument.id)  %>