config/routes.rb
JamWithFriends::Application.routes.draw do
  get "jam_managements/show", to: 'jam_managements#show', as: "jam_managements_show" 
  get "registrations/after_sign_up_path_for"
  root "home#index"
  get "search/index", to: 'search#index', as: "search"
  get "jam_managements/edit_candidates", to: 'jam_managements#edit_candidates', as: "edit_candidates"
  get "jam_managements/update_candidates", to: 'jam_managements#update_candidates', as: "update_candidates"

  get "jam_managements/candidate", to: 'jam_managements#candidate', as: "candidate_to_jam"
  get "jam_managements/withdraw_candidate", to: 'jam_managements#withdraw_candidate', as: "withdraw_candidate_from_jam" 
  get "jam_managements/refuse_infite", to: 'jam_managements#refuse_invite', as: 'refuse_invitation_from_jam'

  get "jam_managements/edit_invite", to: 'jam_managements#edit_invite', as: "edit_invite"
  get "jam_managements/update_invite", to: 'jam_managements#update_invite', as: "update_invite"

  resources :instruments
  resources :genres
  devise_for :users, :controllers => { :registrations => "registrations", :passwords => "passwords"  }
  resources :profile, only: [:show, :edit, :update]
  resources :messages
  resources :conversations
  resources :jams
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :instrxps
  has_many :users, through: :instrxps

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false, message: "instrument already existing" }

  has_many :candidates
  has_many :candidate_jams, through: :candidates, :source => :jam
  has_many :candidate_users, through: :candidates, :source => :user

  has_many :invites
  has_many :invited_users, through: :invites, :source => :user
  has_many :invited_jams, through: :invites, :source => :jam

  has_attached_file :photo, :styles => {:mapmarker => "40x40>"}

  scope :search_by_name, -> (query) {where('lower(name) LIKE :query', :query => "%#{query.downcase}%")}

  def picture_from_url(url)
    self.picture = open(url)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def index
    @instruments = Instrument.all
  end

  def show
    @instrument = Instrument.find params[:id]
  end

  def new
    @instrument = Instrument.new
  end
  
  def create
    @instrument = Instrument.create safe_instrument
    if @instrument.save
      flash[:notice] = "new instrument added!!!"
      redirect_to edit_profile_path(current_user)
    else
      flash[:notice] = "something went wrong with adding #{safe_instrument[:name]}"
      @instrument.save
      @instrument.errors[:name].each do |d| 
        flash[:notice] = flash[:notice] + ", \n #{d}"
      end
      render 'new'
    end
  end

  def edit
    @instrument = Instrument.find params[:id] 
  end
  
  def update 
    @instrument = Instrument.find params[:id]    
    @instrument.update safe_instrument
    if @instrument.save
      flash[:notice] = "instrument edited!!!"
      redirect_to @instrument
    else
      flash[:notice] = "something went wrong"
      render 'edit'
    end
  end

  def destroy
    @instrument = Instrument.find params[:id]
    @instrument.destroy
    flash[:notice] = "#{@instrument.name} has been deleted"
    
    redirect_to instruments_path 
  end

  private

  def safe_instrument
    safe_instrument = params.require(:instrument).permit(:name, :photo)
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/edit.html.erb
<h1>edit the <%= @instrument.name %></h1>
<%= form_for @instrument, :html => {:multipart => true}  do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <%= f.file_field :photo %>
  <%= f.submit %>
<% end %>

app/views/instruments/index.html.erb
<h1>Instruments</h1>
<%= link_to "Add a new Insturment", new_instrument_path %>
<ul>
<% @instruments.each do |instrument| %>
  <li><%= link_to instrument.name, instrument %></li>
<% end %>
</ul>

app/views/instruments/new.html.erb
<h1>Add a new Instrument</h1>
<%= form_for @instrument, :html => {:multipart => true} do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <%= f.file_field :photo %>
  <%= f.submit %>
<% end %>

app/views/instruments/show.html.erb
<h1><%= @instrument.name %></h1>
<p><%= link_to "edit the instrument", edit_instrument_path %>
<p><%= link_to "delete this instrument", instrument_path, confirm: "are you sure",  method: :delete %></p>
<%= image_tag @instrument.photo.url, class: "profile-image-inner" %>
<%= link_to "Back to all instruments", instruments_path %>
<%= link_to "Back home", root_path %>